-- ============================================================================
-- POS Batch Tracking System - FULL INSTALL SCRIPT
-- ============================================================================
-- Use this to set up the database FRESH on a new machine (e.g. from a flash
-- disk install). It creates every table in its final, current form directly -
-- you do NOT need to run any of the old migration_*.sql files after this.
--
-- ONLY run this against a brand-new, empty database. It does not contain any
-- of your existing shop data - if you're moving an existing installation with
-- real records, take a pg_dump of that database instead of using this script.
--
-- Usage:
--   1. Create a new empty database (e.g. `createdb pos_batch_system`)
--   2. Run this file against it:
--        psql -U your_user -d pos_batch_system -f full_install_schema.sql
--      (or paste it into pgAdmin's Query Tool and execute)
--   3. Set PGDATABASE in your .env to match the database name you used
-- ============================================================================
